print("Calculate your BMI using your weight and height. \n")
w = float(input("What is your weight in kg? \n"))
h = float(input("what is your height in m? \n"))
BMI = round(w/h**2)
print(f"Your BMI is: {BMI}")
